# Generated by Django 5.0.6 on 2024-05-19 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(default='', max_length=255)),
                ('Power', models.PositiveIntegerField(default=0)),
                ('Go_to_100', models.FloatField(default=0)),
                ('Max_speed', models.PositiveIntegerField(default=0)),
                ('Type_of_gsb', models.CharField(default='', max_length=14)),
                ('Type_of_drive', models.CharField(default='', max_length=8)),
                ('Img_of_car', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(default=0)),
                ('car', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='racing.cars')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(default='', max_length=255, verbose_name='Имя: ')),
                ('ClientEmail', models.EmailField(default='', max_length=255, verbose_name='Почта: ')),
                ('RentDate', models.DateField(default=None, null=True, verbose_name='Дата: ')),
                ('RentTime', models.CharField(default='', max_length=11, verbose_name='Время: ')),
                ('Car', models.CharField(default='', max_length=50, verbose_name='Авто: ')),
                ('User', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
